<?php
$title = 'Add new application user';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="widget">
	<div class="widget-header">
	    <h3>User Properties</h3>
	</div>
	
	<div class="widget-content">

		<?php
		$form = $this->form;
		$form->setAttribute('action', $this->url('users', array('action' => 'add')));
		$form->get('submit')->setAttribute('Value', 'Add');
		$form->prepare();
		echo $this->form()->openTag($form);
		echo $this->formHidden($form->get('id'));
		?>

		<div class="field"><?php
		echo $this->formLabel($form->get('username'));
		echo $this->formInput($form->get('username'));
		?></div>

		<div class="field"><?php
		echo $this->formLabel($form->get('password'));
		echo $this->formInput($form->get('password'));
		?></div>

		<div class="field"><?php
		echo $this->formLabel($form->get('email'));
		echo $this->formInput($form->get('email'));
		?></div>

		<div class="field"><?php
		echo $this->formLabel($form->get('displayName'));
		echo $this->formInput($form->get('displayName'));
		?></div>

		<?php 
		echo $this->formInput($form->get('submit'));
		echo $this->form()->closeTag($form);
		?>
		
    </div>
</div>