<?php
$title = 'Application Users';
$this->headTitle($title);
$this->headScript()->appendFile('/js/jquery.dataTables.min.js', 'text/javascript');
$this->headScript()->appendFile('/js/application/users/index.js', 'text/javascript');
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a href="<?php echo $this->url('users', array(
'action'=>'add'));?>">Add new user</a></p>

<div class="widget">
	<div class="widget-header">
	    <h3><?php echo $this->escapeHtml($title); ?></h3>
	</div>
	<div class="widget-content">
	    
	    <?php
	    if(!$this->messages == null){
            echo $this->partial('message.phtml', array('message' => $this->messages[0]));
	    }
	    ?>
	    
	    <table class="data">
	        <thead>
    	        <tr>
        	        <th>Username</th>
        	        <th>Email Address</th>
        	        <th>Display Name</th>
        	        <th class="no-sort actions">Actions</th>
    	        </tr>
    	    </thead>
    	    <tbody>
    	    
    	    <?php foreach($users as $user) : ?>
    	    <?php $actions = '<a class="icon edit" title="Edit" href="' . $this->url(
	             'users', array('action'=>'edit', 'id' => $user->getId())) . '"></a>' . 
	           '<a class="icon delete" title="Delete" href="' . $this->url(
	             'users', array('action'=>'delete', 'id' => $user->getId())) . '"></a>';?>
    	    <tr>
    	        <td><?php echo $this->escapeHtml($user->getUsername());?></td>
    	        <td><?php echo $this->escapeHtml($user->getEmail());?></td>
                <td><?php echo $this->escapeHtml($user->getDisplayName());?></td>
    	        <td><?php echo $actions;?></td>
    	    </tr>
            <?php endforeach; ?>
    	    
    	    </tbody>
	    </table>
	</div>
</div>
<div class="hidden" id="total-records"><?php echo $iTotalRecords;?></div>