<?php
$title = 'Stock adjustment';
$this->headTitle($title);
$this->headScript()->appendFile('/js/bootstrap.js', 'text/javascript');
$this->headScript()->appendFile('/js/bootstrap-typeahead.js', 'text/javascript');
$this->headScript()->appendFile('/js/inventory/posting/adjustment.js', 'text/javascript');
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<div class="widget">
	
	<div class="widget-header">
	    <h4>Adjustment Details</h4>
	</div>
	
	<div class="widget-content">
		<?php
		$form = $this->form;
		$form->setAttribute('action', $this->url('inventory/default', array('controller' => 'posting', 'action' => 'adjustment')));
		$form->get('submit')->setAttribute('Value', 'OK');
		echo $this->RenderForm($form);
		?>
    </div>
    
</div>