<?php
    $title = 'Add new calendar event';
    $this->headTitle($title);
    $this->headLink()->appendStylesheet('/css/datepicker.css');
    $this->headScript()->appendFile('/js/bootstrap-datepicker.js', 'text/javascript');
    $this->headScript()->appendFile('/js/application/calendar/add.js', 'text/javascript');
?>

<h3><?php echo $this->escapeHtml($title); ?></h3>
<div class="widget">
	
	<div class="widget-header">
	    <h4>Event details</h4>
	</div>
	
	<div class="widget-content">
		<?php
		$form = $this->form;
		$form->setAttribute('action', $this->url('calendar', array('controller' => 'calendar', 'action' => 'add')));
		$form->get('submit')->setAttribute('Value', 'Add');
		echo $this->RenderForm($form);
		?>
    </div>
    
</div>