<?php
$title = 'Edit inventory item';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('location_code'));
echo $this->formRow($form->get('location_name'));
echo $this->formRow($form->get('contact_name'));
echo $this->formRow($form->get('phone_no'));
echo $this->formRow($form->get('fax_no'));
echo $this->formRow($form->get('email'));
echo $this->formInput($form->get('submit'));
echo $this->form()->closeTag($form);