<?php
    $title = 'Inventory Locations';
    $this->headTitle($title);
    $this->headScript()->appendFile('/js/jquery.dataTables.min.js', 'text/javascript');
    $this->headScript()->appendFile('/js/inventory/locations/index.js', 'text/javascript');
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a href="<?php echo $this->url('locations', array(
'action'=>'add'));?>">Add new inventory location</a></p>

<div class="widget">
    <div class="widget-header">
    </div>
    <div class="widget-content">
        <table class="data">
            <thead>
                <tr>
                    <th>Location Code</th>
                    <th>Description</th>
                    <th class="no-sort actions">Actions</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach($locations as $location) : ?>
            <?php $actions = '<a class="icon edit" title="Edit" href="' . $this->url(
	                 'locations', array('action'=>'edit', 'id' => $location->id)) . '"></a>' . 
	               '<a class="icon delete" title="Delete" href="' . $this->url(
	                 'locations', array('action'=>'delete', 'id' => $location->id)) . '"></a>';?>
                <tr>
                    <td><?php echo $this->escapeHtml($location->location_code);?></td>
                    <td><?php echo $this->escapeHtml($location->location_name);?></td>
                    <td><?php echo $actions;?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<div class="hidden" id="total-records"><?php echo $iTotalRecords;?></div>