<?php
$title = 'Add new inventory item';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<div class="widget">
	
	<div class="widget-header">
	    <h4>Item Properties</h4>
	</div>
	
	<div class="widget-content">
		<?php
		$form = $this->form;
		$form->setAttribute('action', $this->url('inventory/default', array('controller' => 'items', 'action' => 'add')));
		$form->get('submit')->setAttribute('Value', 'Add');
		echo $this->RenderForm($form);
		?>
    </div>
    
</div>