<?php
$title = 'Edit inventory item';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="widget">
	<div class="widget-header">
	    <h3>Item Properties</h3>
	</div>
	
	<div class="widget-content">
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('items', array('action' => 'edit', 'id'=>$this->id)));
$form->get('submit')->setAttribute('value', 'Edit');
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('item_code'));
echo $this->formRow($form->get('short_description'));
echo $this->formRow($form->get('category_id'));
echo $this->formInput($form->get('submit'));
echo $this->form()->closeTag($form);
?>
    </div>
</div>