<?php
    $title = 'Inventory item status enquiry';
    $this->headTitle($title);
    $this->headScript()->appendFile('/js/bootstrap.js', 'text/javascript');
    $this->headScript()->appendFile('/js/bootstrap-typeahead.js', 'text/javascript');
    $this->headScript()->appendFile('/js/inventory/items/enquire.js', 'text/javascript');
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<div class="widget">
	
	<div class="widget-header">
	    <h4>Item</h4>
	</div>
	
	<div class="widget-content">
	
	    <?php
	    if(!$this->messages == null){
            echo $this->partial('message.phtml', array(
                'type' => 'error',
                'message' => $this->messages[0]
            ));
	    }
	    ?>
	    
		<?php
		$form = $this->form;
		$form->setAttribute('action', $this->url('inventory/default', array('controller' => 'items', 'action' => 'enquire')));
		echo $this->RenderForm($form);
		?>
    </div>
    
</div>