<?php
    $title = 'Inventory Items';
    $this->headTitle($title);
    $this->headScript()->appendFile('/js/jquery.dataTables.min.js', 'text/javascript');
    $this->headScript()->appendFile('/js/inventory/items/index.js', 'text/javascript');
?>

<h3><?php echo $this->escapeHtml($title); ?></h3>
<p><a href="<?php echo $this->url('inventory/default', array(
    'controller' => 'items',
    'action'=>'add'
));?>">Add new inventory item</a></p>

<div class="widget">
	<div class="widget-header">
	    <h4><?php echo $this->escapeHtml($title); ?></h4>
	</div>
	<div class="widget-content">
	    
	    <?php
	    if(!$this->messages == null){
            echo $this->partial('message.phtml', array(
                'type' => 'success',
                'message' => $this->messages[0],
            ));
	    }
	    ?>
	    
	    <table class="data">
	        <thead>
    	        <tr>
        	        <th>Item Code</th>
        	        <th>Short Description</th>
        	        <th class="no-sort actions">Actions</th>
    	        </tr>
    	    </thead>
    	    <tbody>
    	    
    	    <?php foreach($items as $item) : ?>
    	    <?php $actions = '<a class="icon edit" title="Edit" href="' . $this->url(
	             'inventory/default', array('controller' => 'items', 'action'=>'edit', 'id' => $item->id)) . '"></a>' . 
	           '<a class="icon delete" title="Delete" href="' . $this->url(
	             'inventory/default', array('controller' => 'items', 'action'=>'delete', 'id' => $item->id)) . '"></a>';?>
    	    <tr>
    	        <td><?php echo $this->escapeHtml($item->item_code);?></td>
                <td><?php echo $this->escapeHtml($item->short_description);?></td>
    	        <td><?php echo $actions;?></td>
    	    </tr>
            <?php endforeach; ?>
    	    
    	    </tbody>
	    </table>
	</div>
</div>
<div class="hidden" id="total-records"><?php echo $iTotalRecords;?></div>