<?php
    $title = 'Inventory Item Movements';
    $this->headTitle($title);
    $this->headScript()->appendFile('/js/jquery.dataTables.min.js', 'text/javascript');
    $this->headScript()->appendFile('/js/inventory/items/movements.js', 'text/javascript');
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>

<div class="widget">
	<div class="widget-header">
	    <h4><?php echo 'Item Movements'; ?></h4>
	</div>
	<div class="widget-content">
	
	    <table class="data">
	        <thead>
    	        <tr>
        	        <th>Date</th>
        	        <th>Item Code</th>
        	        <th>Transaction Type</th>
        	        <th>Qty</th>
        	        <th>Location</th>
    	        </tr>
    	    </thead>
    	    <tbody>
    	    
    	    <?php foreach($transactions as $transaction) : ?>
    	    <tr>
    	        <td><?php echo $transaction->trans_date->format('Y-m-d H:i:s');?></td>
    	        <td><?php echo $transaction->item->item_code;?></td>
                <td><?php echo $transaction->movement_type->name;?></td>
                <td><?php echo $transaction->qty;?></td>
                <td><?php echo $transaction->location->location_name;?></td>
    	    </tr>
            <?php endforeach; ?>
    	    
    	    </tbody>
	    </table>
	
	</div>
</div>
<div class="hidden" id="total-records"><?php echo $iTotalRecords;?></div>
