<?php
$title = 'Inventory Items Valuation';
$this->headTitle($title);
$this->headScript()->appendFile('/js/jquery.dataTables.min.js', 'text/javascript');
$this->headScript()->appendFile('/js/inventory/items/valuation.js', 'text/javascript');
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>

<div class="widget">
	<div class="widget-header">
	    <h4><?php echo 'Items in stock';?></h4>
	</div>
	<div class="widget-content">
	
	    <table class="data">
	        <thead>
    	        <tr>
        	        <th>Item Code</th>
        	        <th>Item Description</th>
        	        <th>Location Code</th>
        	        <th>Location Description</th>
        	        <th>Qty</th>
    	        </tr>
    	    </thead>
    	    <tbody>
    	    
    	    <?php foreach($items as $item) : ?>
    	    <tr>
    	        <td><?php echo $this->escapeHtml($item['item_code']);?></td>
                <td><?php echo $this->escapeHtml($item['short_description']);?></td>
                <td><?php echo $this->escapeHtml($item['location_code']);?></td>
                <td><?php echo $this->escapeHtml($item['location_name']);?></td>
                <td><?php echo $this->escapeHtml($item['1']);?></td>
    	    </tr>
            <?php endforeach; ?>
    	    
    	    </tbody>
	    </table>
	
	</div>
</div>