<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Module'                        => __DIR__ . '/Module.php',
    'Application\Controller\CalendarController' => __DIR__ . '/src/Application/Controller/CalendarController.php',
    'Application\Controller\IndexController'    => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\Controller\RolesController'    => __DIR__ . '/src/Application/Controller/RolesController.php',
    'Application\Controller\UsersController'    => __DIR__ . '/src/Application/Controller/UsersController.php',
    'Application\Entity\Entity'                 => __DIR__ . '/src/Application/Entity/Entity.php',
    'Application\Entity\Event'                  => __DIR__ . '/src/Application/Entity/Event.php',
    'Application\Entity\Role'                   => __DIR__ . '/src/Application/Entity/Role.php',
    'Application\Entity\User'                   => __DIR__ . '/src/Application/Entity/User.php',
    'Application\Form\EventForm'                => __DIR__ . '/src/Application/Form/EventForm.php',
    'Application\Form\RoleForm'                 => __DIR__ . '/src/Application/Form/RoleForm.php',
    'Application\Form\UserForm'                 => __DIR__ . '/src/Application/Form/UserForm.php',
);