<?php
$this->headTitle()->setSeparator(' - ')
                  ->setAutoEscape(false);
$basePath = $this->basePath();

// Stylesheets
$this->headLink()->appendStylesheet($basePath . '/css/bootstrap.min.css')
                 ->appendStylesheet($basePath . '/css/style.css')
                 ->appendStylesheet($basePath . '/css/bootstrap-responsive.min.css')
                 ->appendStylesheet($basePath . '/css/data.css');

// Favicon
$this->headLink(array(
            'rel'  => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $basePath . '/images/favicon.ico',
        ));

// HTML5 shim, for IE6-8 support of HTML elements
$this->headScript()->appendFile($basePath . '/js/html5.js', 'text/javascript',
    array('conditional' => 'lt IE 9',));

// JQuery.
$this->headScript()->prependFile($basePath . '/js/jquery-1.7.2.min.js', 'text/javascript');

// Doctype.
echo $this->doctype();
?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Platinum Application') ?>

    <!--  Meta data -->
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Styles -->
    <?php echo $this->headLink() ?>

    <!-- Scripts -->
    <?php echo $this->headScript() ?>

</head>

<body>
  
    <!-- Header -->
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->url('default') ?>">Platinum Application</a>
          <div class="nav-collapse">
              <?php  echo $this->navigation('Navigation')->menu()->setUlClass('nav'); ?>
               
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
  
  <!-- Content -->
  <div class="container">
       
      <?php echo $this->content; ?>
  
      <hr>
      <p>&copy; 2012 by Civray Software. All rights reserved.</p>
  </div>

</body>
</html>
