<?php
    $title = 'Add order line item';
    $this->headTitle($title);
?>

<h2>Add Item to Order <?php echo $this->order->getId();?></h2>

<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('sales/default', array('controller' => 'order', 'action' => 'addline', 'id' => $this->order->getId())));
    $form->get('submit')->setAttribute('Value', 'Add');
    echo $this->RenderForm($form);
?>