<h2>Sales Order Detail</h2>

<p><a href="<?php echo $this->url('sales/default', array(
    'controller' => 'order'
        ));?>">Back to Sales orders</a></p>

<table class="table table-bordered table-condensed">
    <tr>
        <th>Order No</th>
        <td><?php echo $this->order->getId();?></td>
    </tr>
    <tr>
        <th>Order Date</th>
        <td><?php echo $this->order->getOrderDate()->format('d/m/Y');?></td>
    </tr>
    <tr>
        <th>Customer Ref</th>
        <td><?php echo $this->order->getCustomerRef();?></td>
    </tr>
    <tr>
        <th>Order Status</th>
        <td><?php echo $this->order->getOrderStatus();?></td>
    </tr>
</table>

<table class="data dataTable">
    <thead>
        <tr>
            <th>Line No</th>
            <th>Item Code</th>
            <th>Qty</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php $i = 1;?>
        <?php foreach($order->getLines() as $item):?>
        <tr>
            <?php $actions = '<a class="icon edit" title="Edit" href="' . $this->url(
	        'sales/default', array('controller' => 'order', 'action'=>'editline', 'id' => $item->getId())) . '"></a>' . 
	        '<a class="icon delete" title="Delete" href="' . $this->url(
	        'sales/default', array('controller' => 'order', 'action'=>'deleteline', 'id' => $item->getId())) . '"></a>';?>
            <td><?php echo $i;?></td>
            <td><?php echo $item->getItem()->item_code;?></td>
            <td><?php echo $item->getQty();?></td>
            <td><?php echo $item->getOrderStatus();?></td>
            <td><?php echo $actions;?></td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>
<br>

<p><a href="<?php echo $this->url('sales/default', array(
    'controller' => 'order',
    'action' => 'addline',
    'id' => $this->order->getId()
        ));?>">Add item to order</a></p>

<p><a href="<?php echo $this->url('sales/default', array(
    'controller' => 'order',
    'action' => 'acknowledge',
    'id' => $this->order->getId()
        ));?>">Acknowledge order</a></p>