<h2>Sales Order Detail</h2>

<p><a href="<?php echo $this->url('sales/default', array(
    'controller' => 'order'
        ));?>">Back to Sales orders</a></p>

<table class="table table-bordered">
    <tr>
        <th>Order No</th>
        <td><?php echo $this->order->getId();?></td>
    </tr>
    <tr>
        <th>Order Date</th>
        <td><?php echo $this->order->getOrderDate()->format('d/m/Y');?></td>
    </tr>
    <tr>
        <th>Customer Ref</th>
        <td><?php echo $this->order->getCustomerRef();?></td>
    </tr>
</table>