<?php
$title = 'Create new sales order';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<div class="widget">
	
	<div class="widget-header">
	    <h4>Order Details</h4>
	</div>
	
	<div class="widget-content">
		<?php
		$form = $this->form;
		$form->setAttribute('action', $this->url('sales/default', array('controller' => 'order', 'action' => 'edit', 'id' => $this->id)));
		$form->get('submit')->setAttribute('Value', 'Edit');
		echo $this->RenderForm($form);
		?>
    </div>
    
</div>