<?php
    $title = 'Sales Orders';
    $this->headTitle($title);
    $this->headScript()->appendFile('/js/jquery.dataTables.min.js', 'text/javascript');
    $this->headScript()->appendFile('/js/sales/order/index.js', 'text/javascript');
?>

<h3><?php echo $this->escapeHtml($title); ?></h3>
<p><a href="<?php echo $this->url('sales/default', array(
    'controller' => 'order',
    'action'=>'create'
));?>">Create new sales order</a></p>

<div class="widget">
    <div class="widget-header">
        <h4><?php echo $this->escapeHtml($title); ?></h4>
    </div>
    <div class="widget-content">
        
        <table class="data">
            <thead>
                <tr>
                    <th>Order Number</th>
                    <th>Order Date</th>
                    <th>Customer Ref</th>
                    <th class="no-sort actions">Actions</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach($orders as $order) : ?>
            <?php $actions = '<a class="icon edit" title="Edit" href="' . $this->url(
	        'sales/default', array('controller' => 'order', 'action'=>'edit', 'id' => $order->getId())) . '"></a>' . 
	        '<a class="icon delete" title="Delete" href="' . $this->url(
	        'sales/default', array('controller' => 'order', 'action'=>'delete', 'id' => $order->getId())) . '"></a>';?>
                <tr>
                    <td><?php echo $this->escapeHtml($order->getId());?></td>
                    <td><?php echo $order->getOrderDate()->format('d/m/Y');?></td>
                    <td><?php echo $this->escapeHtml($order->getCustomerRef());?></td>
                    <td><?php echo $actions;?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<div class="hidden" id="total-records"><?php echo $iTotalRecords;?></div>