<?php
$title = 'Delete unit of measure';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<div class="widget">

    <div class="widget-header">
	    <h4>Delete unit of measure</h4>
	</div>
	
	<div class="widget-content">
	
        <p>Are you sure that you want to delete
        '<?php echo $this->escapeHtml($unit['name']); ?>',?
        </p>
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('inventory/default', array('controller' => 'units', 'action' => 'delete', 'id'=>$this->id)));
        echo $this->RenderForm($form);
        $url = $this->url('inventory/default', array('controller' => 'units', 'action' => 'delete', 'id'=>$this->id)); ?>
    
    </div>

</div>