<?php
$title = 'Add new sales area';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>
<div class="widget">
	
    <div class="widget-header">
        <h4>Area Details</h4>
    </div>
	
    <div class="widget-content">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('sales/default', array('controller' => 'area', 'action' => 'add')));
        $form->get('submit')->setAttribute('Value', 'Add');
        echo $this->RenderForm($form);
        ?>
    </div>
    
</div>