<?php
    $title = 'Sales Areas';
    $this->headTitle($title);
    $this->headScript()->appendFile('/js/jquery.dataTables.min.js', 'text/javascript');
    $this->headScript()->appendFile('/js/sales/area/index.js', 'text/javascript');
?>

<h3><?php echo $this->escapeHtml($title); ?></h3>
<p><a href="<?php echo $this->url('sales/default', array(
    'controller' => 'area',
    'action'=>'add'
));?>">Add new sales area</a></p>

<div class="widget">
    <div class="widget-header">
        <h4><?php echo $this->escapeHtml($title); ?></h4>
    </div>
    <div class="widget-content">
  
        <?php
	    if(!$this->messages == null){
                echo $this->partial('message.phtml', array(
                    'type' => 'success',
                    'message' => $this->messages[0]
                ));
	    }
	?>
	    
        <table class="data">
            <thead>
                <tr>
                    <th>Code</th>
                    <th>Description</th>
                    <th class="no-sort actions">Actions</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach($areas as $area) : ?>
            <?php $actions = '<a class="icon edit" title="Edit" href="' . $this->url(
	        'sales/default', array('controller' => 'area', 'action'=>'edit', 'id' => $area->getId())) . '"></a>' . 
	        '<a class="icon delete" title="Delete" href="' . $this->url(
	        'sales/default', array('controller' => 'area', 'action'=>'delete', 'id' => $area->getId())) . '"></a>';?>
                <tr>
                    <td><?php echo $this->escapeHtml($area->getCode());?></td>
                    <td><?php echo $this->escapeHtml($area->getDescription());?></td>
                    <td><?php echo $actions;?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<div class="hidden" id="total-records"><?php echo $iTotalRecords;?></div>