<h3>Transactions</h3>

<a href="<?php echo $this->url('sales/default', array(
    'controller' => 'order',
    'action'     =>'create'
));?>">Create Sales Order</a><br>

<a href="<?php echo $this->url('sales/default', array(
        'controller' => 'order',
        'action'     => 'ship'
));?>">Ship Sales Order</a><br>

<br>

<h3>Enquiries &amp Reports</h3>
<a href="<?php echo $this->url('sales/default', array(
    'controller' => 'order'
));?>">View Sales Orders</a><br>

<br>

<h3>Maintenance</h3>
<a href="<?php echo $this->url('sales/default', array(
    'controller'=>'account'
));?>">Customer Accounts</a><br>
<a href="<?php echo $this->url('sales/default', array(
    'controller'=>'branch'
));?>">Sales Branches</a><br>
<a href="<?php echo $this->url('sales/default', array(
    'controller'=>'area'
));?>">Sales Areas</a><br>
