<?php

// Output
$output = array(
		"sEcho" => $sEcho,
		"iTotalRecords" => $iTotalRecords,
		"iTotalDisplayRecords" => $iTotalDisplayRecords,
		"aaData" => array()
);

foreach($categories as $category)
{
	$actions = '<a class="icon edit" title="Edit" href="' . $this->url(
	        'inventory/default', array('controller' => 'categories', 'action'=>'edit', 'id' => $category->id)) . '"></a>' .
	    '<a class="icon delete" title="Delete" href="' . $this->url(
			'inventory/default', array('controller' => 'categories', 'action'=>'delete', 'id' => $category->id)) . '"></a>';
	 
	$row = array();
	$row[] = $this->escapeHtml($category->name);
	$row[] = $actions;
	$output['aaData'][] = $row;
}
echo json_encode($output);