<?php
    $title = 'Inventory Categories';
    $this->headTitle($title);
    $this->headScript()->appendFile('/js/jquery.dataTables.min.js', 'text/javascript');
    $this->headScript()->appendFile('/js/inventory/categories/index.js', 'text/javascript');
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a href="<?php echo $this->url('categories', array(
'action'=>'add'));?>">Add new inventory category</a></p>

<div class="widget">
  <div class="widget-header">
    <h3><?php echo $this->escapeHtml($title); ?></h3>
  </div>
  <div class="widget-content">
  
      <?php
	    if(!$this->messages == null){
            echo $this->partial('message.phtml', array('message' => $this->messages[0]));
	    }
	  ?>
	    
    <table class="data">
        <thead>
            <tr>
                <th>Name</th>
                <th class="no-sort actions">Actions</th>
            </tr>
        </thead>
        <tbody>
    
            <?php foreach($categories as $category) : ?>
            <?php $actions = '<a class="icon edit" title="Edit" href="' . $this->url(
	                 'categories', array('action'=>'edit', 'id' => $category->id)) . '"></a>' . 
	               '<a class="icon delete" title="Delete" href="' . $this->url(
	                 'categories', array('action'=>'delete', 'id' => $category->id)) . '"></a>';?>
            <tr>
              <td><?php echo $this->escapeHtml($category->name);?></td>
              <td><?php echo $actions;?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
  </div>
</div>
<div class="hidden" id="total-records"><?php echo $iTotalRecords;?></div>