
<a href="<?php echo $this->url('inventory');?>"><h3>Inventory</h3></a>
<p>Inventory control management module. From here you can view and manage current stock, review past stock
movements and setup new inventory items.</p>

<a href="<?php echo $this->url('default');?>"><h3>Sales</h3></a>
<p>Sales order processing module. This module manages the life cycle of sales orders from order entry through to
payment receipt. From here you can manage customer accounts, sales orders and invoicing.</p>

<a href="<?php echo $this->url('default');?>"><h3>Purchasing</h3></a>
<p>Purchase order processing module. This module manages the life cycle of purchase orders from order entry through
to payment. From here you can manage purchase orders, suppliers accounts and goods receipts. </p>
