
<h3>Transactions</h3>
<a href="<?php echo $this->url('items', array(
	'action'=>'transfer'
));?>">Inventory Location Transfers</a><br>
<a href="<?php echo $this->url('items', array(
	'action'=>'adjust'
));?>">Inventory Adjustments</a><br><br>

<h3>Inquiries &amp Reports</h3>
<a href="<?php echo $this->url('items', array(
    'action'=>'status'
));?>">Item Status</a><br>
<a>Movements</a><br>
<a>Valuation Report</a><br>
<a>Stock check sheets</a><br><br>

<h3>Maintenance</h3>
<a href="<?php echo $this->url('items', array(
    'action'=>'index'
));?>">Items</a><br>
<a href="<?php echo $this->url('categories', array(
    'action'=>'index'
));?>">Item Categories</a><br>
<a href="<?php echo $this->url('locations', array(
    'action'=>'index'
));?>">Inventory Locations</a><br>
<a>Movement Types</a><br>
<a>Units of Measure</a><br>
<a>Sales Pricing</a><br>