<h3>Transactions</h3>
<a href="<?php echo $this->url('items', array(
	'action'=>'transfer'));?>">System Users</a><br>
<a href="<?php echo $this->url('items', array(
	'action'=>'adjust'));?>">Inventory Adjustments</a><br>

<br>
<h3>Inquiries &amp Reports</h3>
<a href="<?php echo $this->url('items', array(
	'action'=>'status'));?>">System Info</a><br>
<a>Event Log</a><br>

<br>
<h3>Maintenance</h3>
<a href="<?php echo $this->url('users', array(
	'action'=>'index'));?>">System Users</a><br>
<a href="<?php echo $this->url('roles', array(
	'action'=>'index'));?>">User Roles</a><br>
