<h1>Sign In</h1>

<div class="widget">
    <div class="widget-header">
        <h3>Sign In</h3>
    </div>
    <div class="widget-content">

        <?php
        $form = $this->loginForm;
        $form->prepare();
        $form->setAttribute('action', $this->url('zfcuser/login'));
        $form->setAttribute('method', 'post');
        ?>

        <?php echo $this->form()->openTag($form) ?>

        <dl class="zend_form">
            <?php echo $this->formElementErrors($form->get('identity')) ?>

            <dt><?php echo $this->formLabel($form->get('identity')) ?></dt>
            <dd><?php echo $this->formInput($form->get('identity')) ?></dd>

            <dt><?php echo $this->formLabel($form->get('credential')) ?></dt>
            <dd><?php echo $this->formInput($form->get('credential')) ?></dd>

            <?php if ($this->redirect): ?>
                <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
            <?php endif ?>

            <dd><?php echo $this->formButton($form->get('submit')) ?></dd>
        </dl>

        <?php echo $this->form()->closeTag() ?>
    </div>
</div>

Not registered? <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">Sign up!</a>
